FROM apache/airflow:2.8.1

USER root

RUN apt-get update && \
    apt-get install -y \
    openjdk-17-jdk \
    procps \
    && apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow

RUN pip install --no-cache-dir \
    pyspark==3.4.1 \
    delta-spark==2.4.0